language: python
python:
    - "2.7"

install:
    # todo: fix dependecies mismatch and use python setup.py install instead
    - 'if [ ${TRAVIS_BRANCH} \!= "master" ] && [ -f dev_requirements.txt ]; then
        pip install --extra-index-url https://testpypi.python.org/pypi -r dev_requirements.txt;
        python setup.py develop --no-deps;
      else
        pip install -r requirements.txt;
        python setup.py develop --no-deps;
      fi'
    - pip install -r test_requirements.txt
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-package=cloudshell.networking.huawei tests

after_success:
    - coveralls